### ISSUE TITLE
Linker errors building on Windows under Visual Studio 2019/2022

### ISSUE THREAD

**Issue by samuel-rice** [cycfi/artist#10]
I've tried this on two laptops. With VS 2019 I get the following command line output:
[artist_build_log.txt](https://github.com/cycfi/artist/files/7576693/artist_build_log.txt)

I get what look like the same errors from VS 2022, so I'll omit the logs for that one. Both laptops are running Windows 10, and I'm building the master/develop branch (they are currently both at e5c51b5497f7927a71cac77b0fe6de84c461ce84).

There are also errors copying the prebuilt dlls. I had a mild hunch that it could be something with file permissions, but file permissions on Windows are a mystery to me, and my attempts to manually remove any restrictions on the dlls didn't help.

**Comment by djowel** [comment]
Confirmed. I am getting the same build errors.

**Comment by djowel** [comment]
In my case, VS is not able to copy the dll into target directories. For example the artist/build/test/Debug 

Can you see if the folders are not read only and if they are, can you set it to read-write? In my case it's always reverting to read-only, even after I set it to read-write. I'm investigating, but this seems to be a windows issue.

**Comment by djowel** [comment]
OK, I think I I found it: VS is trying to copy "build/windows-x64-dll/src/dlls/libiconv.dll" but it's not there. What's there instead is build\windows-x64-dll\src\windows_dll\libiconv.dll

Still investigating.

**Comment by djowel** [comment]
OK, this is the culprit: https://github.com/cycfi/artist/blob/master/CMakeLists.txt#L48-L51

Somehow, it was renamed from "dll" to "windows_dll". Now I am looking at the libunibreak. It seems like binary incmpatibility with the library on Debug build. Release works fine. Try it.

**Comment by djowel** [comment]
OK, it is fixed now. Everything builds and runs fine.

**Comment by djowel** [comment]
Please confirm fix and feel free to close this once confirmed

**Comment by samuel-rice** [comment]
Yep, that's done the trick, thanks!
